version: '3.7'

services:
  passboltdb:
    image: mariadb:10.3
    env_file:
      - mysql.env
    volumes:
      - passboltdb:/var/lib/mysql

  passbolt:
    image: teecke/gp-passbolt:0.2.1
    ports:
      - 4004:80
    tty: true
    depends_on:
      - passboltdb
    env_file:
      - passbolt.env
    volumes:
      - ./data/var/www/passbolt/config/gpg:/var/www/passbolt/config/gpg
      - ./data/var/www/passbolt/webroot/img/public:/var/www/passbolt/webroot/img/public
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "db:3306", "-t", "60", "--", "/docker-entrypoint.sh"]

networks:
    default:
      external:
        name: platform_services

volumes:
  passboltdb: